replicaCount: 1

image:
    repository: 7imbrook/auth
    sha: sha256:48b65d559a906f8f5c2621a733567ebbbb6ddf20576a38b5c7b195cabaab357e 

healthEndpoint: "/api/v1/status"

container:
  port: 3000

ingress:
    enabled: true
    hosts:
        - timbrook.tech
        - timbrook.dev
        - timbrook.life
    paths:
        - /api/v1

resources:
  limits:
   cpu: 80m
   memory: 128Mi
  requests:
   cpu: 20m
   memory: 56Mi