replicaCount: 1

image:
    repository: 7imbrook/auth
    sha: sha256:beeb59dd52b3c7d5c20c0c6430b392de3817f0e4e3f68850374e49c09156bb53 

healthEndpoint: "/api/v1/status"

container:
  port: 3000

ingress:
    enabled: true
    hosts:
        - timbrook.tech
        - timbrook.dev
        - timbrook.life
    paths:
        - /api/v1

resources:
  limits:
   cpu: 80m
   memory: 128Mi
  requests:
   cpu: 20m
   memory: 56Mi

vault:
  enabled: true
  host: "http://vault.core.svc.cluster.local:8200"
  role: "auth-server"